# **Introduction to Numpy**

NumPy (Numerical Python) is a fundamental library for scientific computing in Python. It provides:

1. A powerful N-dimensional array object

2. Sophisticated broadcasting functions

3. Tools for integrating C/C++ code

4. Linear algebra, Fourier transform, and random number capabilities


## **Why NumPy?**

1. Performance: NumPy arrays are much faster than Python lists for numerical operations

2. Memory Efficiency: NumPy uses less memory than Python lists

3. Convenience: NumPy provides many mathematical functions and tools

4. Foundation: Many other data science libraries (Pandas, Matplotlib, scikit-learn) are built on NumPy

In [1]:
# import numpy
import numpy as np

# check the version
version = np.__version__
print(version)

2.0.2


# **Create Numpy Arrays**

Arrays are the main data structure in NumPy. An array is a collection of elements of the same data type, and can have any number of dimensions. A one
dimensional array is called a vector, while a two-dimensional array is called a
matrix.

In [7]:
# create array
arr1 = np.array([1, 2, 3, 4, 5])

# from python list
list1 = [1, 2, 3, 4, 5]
arr1 = np.array(list1)
print(f"1d array:{arr1}")

# 2d array from a nested list
list2 = [[1, 2, 3], [4, 5, 6]]
arr2 = np.array(list2)
print(f"2d array:\n{arr2}")


1d array:[1 2 3 4 5]
2d array:
[[1 2 3]
 [4 5 6]]


### Built-in arrays

In [9]:
# array of zeros: 1d array with 5 zeros, 3x4 array with zeros
arr3 = np.zeros(5)
print(f"zero array: {arr3}")

arr4 = np.zeros((3, 4))
print(f"zero array:\n{arr4}")

# array of ones
arr5 = np.ones(5)
print(f"\n ones array: \n {arr5}")

zero array: [0. 0. 0. 0. 0.]
zero array:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

 ones array: 
 [1. 1. 1. 1. 1.]


In [10]:
# array with a speicific value: 1d arr with six sevens, 2x2 arr of fives
arr = np.full(6, 7)
print(f"array of sevens: {arr}")

array of sevens: [7 7 7 7 7 7]


In [11]:
# array with evenly spaced values
# values from 0-9
arr = np.arange(10)
print(f"array from 0-9: {arr}")

# values from 0-18, step 2
arr9 = np.arange(0, 20, 2)
print(f"\n array from 0-18, step 2:\n {arr9}")

array from 0-9: [0 1 2 3 4 5 6 7 8 9]

 array from 0-18, step 2:
 [ 0  2  4  6  8 10 12 14 16 18]


In [12]:
# create identity matrix
id_matrix = np.eye(3)
print(f"identity matrix:\n {id_matrix}")

identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Random Arrays

In [ ]:
# set seed for reproducibility
np.random.seed(42) # ensure the same sequence of random numbers is generated when the code is run

In [13]:
# random integers: let's get 10 random integers from 0 to 19
random_ints = np.random.randint(0, 20, 10)
print(f"random integers: {random_ints}")


random integers: [ 0 16  1  0 19  9  7  4  7 19]


# **Vectorization**

Vectorized computation is a key feature of NumPy that allows for fast computations on arrays. Instead of performing operations on individual elements, NumPy can perform operations on entire arrays at once, which is much faster.

In [14]:
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1 + 5)

[ 6  7  8  9 10]


# **Array attributes and information**

In [15]:
# create a sample 2d array
sample_array = np.array([[1, 2, 3], [4, 5, 6]])
sample_array

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
# shape
print(f"shape: {sample_array.shape}")

shape: (2, 3)


In [17]:
# number of dimensions
sample_array.ndim

2

In [18]:
# size
sample_array.size

6

In [19]:
# data type
sample_array.dtype

dtype('int64')

In [20]:
# Item size (bytes per element)
sample_array.itemsize

8

In [21]:
# total memory usage
sample_array.nbytes

48

# **Array Indexing and slicing**

Numpy arrays can be indexed and sliced similarly to python lists

In [24]:
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [25]:
# first item
print(arr[0])

1


In [26]:
# first 3 items
print(arr[:3])

[1 2 3]


In [28]:
# from 2 to 5
print(arr[1:5])

[2 3 4 5]


In [29]:
# every second item
print(arr[::2])

[1 3 5]


In [30]:
# reversed array
print(arr[::-1])

[5 4 3 2 1]


# **Reshaping Arrays**

Changing the shape of array without changing the data

In [39]:
arr = np.arange(12)
print(arr)
print(f"\n shape: {arr.shape}")

[ 0  1  2  3  4  5  6  7  8  9 10 11]

 shape: (12,)


In [41]:
# reshape to 2d (3x4)
new_arr = arr.reshape(3, 4)
print(new_arr)
print(f"\n shape: {new_arr.shape}")

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 shape: (3, 4)


In [49]:
new_arr1 = new_arr.reshape(4, 3)
print(new_arr1)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [51]:
# reshape to 3d
arr_3d = new_arr1.reshape(2, 2, 3)
print(arr_3d)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [47]:
# automatically calculate the number of columns in an array
arr_auto = new_arr.reshape(3, -1)
arr_auto

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [48]:
# flatten array
flat_arr = new_arr.flatten()
flat_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])